### ISSUE TITLE
卸载软件的时候无法TAB补全，每次都要list搜一下然后卸载。

### ISSUE THREAD

**Issue by qiqiqiao** [AOSC-Dev/oma#120]
或者是我操作有问题？ 希望卸载软件可以自动补全已安装的软件名称，谢谢
oma remove xxx

**Comment by MingcongBai** [comment]
请问您在用的是什么系统？

**Comment by qiqiqiao** [comment]
> 请问您在用的是什么系统？在安同 OS 是没有问题的，remove 命令可以搭配补全使用

用的就是安同最新版X86系统，我这里补全出来的是oma的参数，没有软件名
![Snipaste_2024-09-26_15-55-41](https://github.com/user-attachments/assets/dcbb26b0-937e-4fa3-b674-d5ac1067c386)

**Comment by qiqiqiao** [comment]
> > > 请问您在用的是什么系统？在安同 OS 是没有问题的，remove 命令可以搭配补全使用
> > 
> > 
> > 用的就是安同最新版X86系统，我这里补全出来的是oma的参数，没有软件名 ![Snipaste_2024-09-26_15-55-41](https://private-user-images.githubusercontent.com/39161054/371062471-dcbb26b0-937e-4fa3-b674-d5ac1067c386.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDEzOTYsIm5iZiI6MTcyNzM0MTA5NiwicGF0aCI6Ii8zOTE2MTA1NC8zNzEwNjI0NzEtZGNiYjI2YjAtOTM3ZS00ZmEzLWI2NzQtZDVhYzEwNjdjMzg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA4NTgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3ZTBkNWU0ODNlZGUzM2FhY2MyNzhiODdhNWFlOTAwZWYxYTFkYjcwMWZiN2Q4OGVmMzcxMzgxYTgyMGMwZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ybgBZfIPSMdQYJ2ahlmGgsc8dMcOz4kZrQK04LhIFBQ)
> 
> 呃，如果您删除掉目前命令中的 `-` 呢？

这个 ‘-’ 不是我加的，是自动补全上去的。。

**Comment by MingcongBai** [comment]
> > > > 请问您在用的是什么系统？在安同 OS 是没有问题的，remove 命令可以搭配补全使用
> > > 
> > > 
> > > 用的就是安同最新版X86系统，我这里补全出来的是oma的参数，没有软件名 ![Snipaste_2024-09-26_15-55-41](https://private-user-images.githubusercontent.com/39161054/371062471-dcbb26b0-937e-4fa3-b674-d5ac1067c386.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDEzOTYsIm5iZiI6MTcyNzM0MTA5NiwicGF0aCI6Ii8zOTE2MTA1NC8zNzEwNjI0NzEtZGNiYjI2YjAtOTM3ZS00ZmEzLWI2NzQtZDVhYzEwNjdjMzg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA4NTgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3ZTBkNWU0ODNlZGUzM2FhY2MyNzhiODdhNWFlOTAwZWYxYTFkYjcwMWZiN2Q4OGVmMzcxMzgxYTgyMGMwZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ybgBZfIPSMdQYJ2ahlmGgsc8dMcOz4kZrQK04LhIFBQ)
> > 
> > 
> > 呃，如果您删除掉目前命令中的 `-` 呢？
> 
> 这个 ‘-’ 不是我加的，是自动补全上去的。。

喔，我明白了，加上 sudo 后就会遇到这个问题；我一般习惯不加 sudo 用，所以没发现问题

cc @eatradish

**Comment by qiqiqiao** [comment]
然后apt卸载补全也是报错
![Uploading Snipaste_2024-09-26_16-00-32.png…]()

**Comment by MingcongBai** [comment]
> 然后apt卸载补全也是报错 ![Snipaste_2024-09-26_16-00-32](https://private-user-images.githubusercontent.com/39161054/371064550-ffccc825-0c63-474d-8d94-6883e86ed1e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDE2NDIsIm5iZiI6MTcyNzM0MTM0MiwicGF0aCI6Ii8zOTE2MTA1NC8zNzEwNjQ1NTAtZmZjY2M4MjUtMGM2My00NzRkLThkOTQtNjg4M2U4NmVkMWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA5MDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1NmVlNTk5MjVjZmUwM2FhMmM5YzRkYTgzNDg0MGE1NzEwZjdjM2MxM2VkMmViMTc2NTUyYzJiOWQ4ZTFlNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aU0ja4tlyBHIwc14_bWmHqVv_FBrgVN7GU6ZititVZQ)

apt 问题麻烦您去 https://github.com/AOSC-Dev/aosc-os-abbs 报告一下

**Comment by qiqiqiao** [comment]
> > 然后apt卸载补全也是报错 ![Snipaste_2024-09-26_16-00-32](https://private-user-images.githubusercontent.com/39161054/371064550-ffccc825-0c63-474d-8d94-6883e86ed1e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDE2NDIsIm5iZiI6MTcyNzM0MTM0MiwicGF0aCI6Ii8zOTE2MTA1NC8zNzEwNjQ1NTAtZmZjY2M4MjUtMGM2My00NzRkLThkOTQtNjg4M2U4NmVkMWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA5MDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1NmVlNTk5MjVjZmUwM2FhMmM5YzRkYTgzNDg0MGE1NzEwZjdjM2MxM2VkMmViMTc2NTUyYzJiOWQ4ZTFlNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aU0ja4tlyBHIwc14_bWmHqVv_FBrgVN7GU6ZititVZQ)
> 
> apt 问题麻烦您去 https://github.com/AOSC-Dev/aosc-os-abbs 报告一下

apt这个无所谓，主要想用oma哈

**Comment by eatradish** [comment]
> 或者是我操作有问题？ 希望卸载软件可以自动补全已安装的软件名称，谢谢 oma remove xxx

你好这个是设计不是 bug，因为我怕用户补全出不对的包名，`remove` 操作还是应该自己输入确认比较好。

**Comment by eatradish** [comment]
> 然后apt卸载补全也是报错 ![Snipaste_2024-09-26_16-00-32](https://private-user-images.githubusercontent.com/39161054/371064550-ffccc825-0c63-474d-8d94-6883e86ed1e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDE4NTEsIm5iZiI6MTcyNzM0MTU1MSwicGF0aCI6Ii8zOTE2MTA1NC8zNzEwNjQ1NTAtZmZjY2M4MjUtMGM2My00NzRkLThkOTQtNjg4M2U4NmVkMWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA5MDU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNTRjYjUxOGJkYjIzOWU0NGM1ZmM2M2E5OTgwNzA4ZWRmMmQwYzFmNTBkYjM5MzczYWU0OWM4YTAxNGQ2NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L_qgaT7Dht2qb-M2OkSlyqRkJIVWTXYPILZZiNxstxY)

这个也是 `apt` 的设计使然

**Comment by qiqiqiao** [comment]
> > 或者是我操作有问题？ 希望卸载软件可以自动补全已安装的软件名称，谢谢 oma remove xxx
> 
> 你好这个是设计不是 bug，因为我怕用户补全出不对的包名，`remove` 操作还是应该自己输入确认比较好。

可是用了安同linux的会有小白吗？ 毕竟软件商店都没有，安装软件还要命令行的。。 或者能否给一个选项呢？

**Comment by MingcongBai** [comment]
> > 然后apt卸载补全也是报错 ![Snipaste_2024-09-26_16-00-32](https://private-user-images.githubusercontent.com/39161054/371064550-ffccc825-0c63-474d-8d94-6883e86ed1e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDE4NTEsIm5iZiI6MTcyNzM0MTU1MSwicGF0aCI6Ii8zOTE2MTA1NC8zNzEwNjQ1NTAtZmZjY2M4MjUtMGM2My00NzRkLThkOTQtNjg4M2U4NmVkMWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA5MDU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNTRjYjUxOGJkYjIzOWU0NGM1ZmM2M2E5OTgwNzA4ZWRmMmQwYzFmNTBkYjM5MzczYWU0OWM4YTAxNGQ2NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L_qgaT7Dht2qb-M2OkSlyqRkJIVWTXYPILZZiNxstxY)
> 
> 这个也是 `apt` 的设计使然

恐怕不是，我刚刚在 Debian 上发现 `apt remove` 确实可以补全包名，上面的现象恐怕确实是我们这边的补全打包有问题

至于 oma 部分的设计，二位继续讨论

**Comment by qiqiqiao** [comment]
> > > 然后apt卸载补全也是报错 ![Snipaste_2024-09-26_16-00-32](https://private-user-images.githubusercontent.com/39161054/371064550-ffccc825-0c63-474d-8d94-6883e86ed1e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDE4NTEsIm5iZiI6MTcyNzM0MTU1MSwicGF0aCI6Ii8zOTE2MTA1NC8zNzEwNjQ1NTAtZmZjY2M4MjUtMGM2My00NzRkLThkOTQtNjg4M2U4NmVkMWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA5MDU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNTRjYjUxOGJkYjIzOWU0NGM1ZmM2M2E5OTgwNzA4ZWRmMmQwYzFmNTBkYjM5MzczYWU0OWM4YTAxNGQ2NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L_qgaT7Dht2qb-M2OkSlyqRkJIVWTXYPILZZiNxstxY)
> > 
> > 
> > 这个也是 `apt` 的设计使然
> 
> 恐怕不是，我刚刚在 Debian 上发现 `apt remove` 确实可以补全包名，上面的现象恐怕确实是我们这边的补全打包有问题
> 
> 至于 oma 部分的设计，二位继续讨论

那还挺奇怪的，我用虚拟机和电脑安装都是一样的。安装软件可以补全 但是卸载不行

**Comment by MingcongBai** [comment]
> > > > 然后apt卸载补全也是报错 ![Snipaste_2024-09-26_16-00-32](https://private-user-images.githubusercontent.com/39161054/371064550-ffccc825-0c63-474d-8d94-6883e86ed1e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDE4NTEsIm5iZiI6MTcyNzM0MTU1MSwicGF0aCI6Ii8zOTE2MTA1NC8zNzEwNjQ1NTAtZmZjY2M4MjUtMGM2My00NzRkLThkOTQtNjg4M2U4NmVkMWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA5MDU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNTRjYjUxOGJkYjIzOWU0NGM1ZmM2M2E5OTgwNzA4ZWRmMmQwYzFmNTBkYjM5MzczYWU0OWM4YTAxNGQ2NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L_qgaT7Dht2qb-M2OkSlyqRkJIVWTXYPILZZiNxstxY)
> > > 
> > > 
> > > 这个也是 `apt` 的设计使然
> > 
> > 
> > 恐怕不是，我刚刚在 Debian 上发现 `apt remove` 确实可以补全包名，上面的现象恐怕确实是我们这边的补全打包有问题
> > 至于 oma 部分的设计，二位继续讨论
> 
> 那还挺奇怪的，我用虚拟机和电脑安装都是一样的。安装软件可以补全 但是卸载不行

我的意思是，安同这边的 apt 补全恐怕有问题，oma 这边我们再研讨下怎么做

**Comment by qiqiqiao** [comment]
> > > > > 然后apt卸载补全也是报错 ![Snipaste_2024-09-26_16-00-32](https://private-user-images.githubusercontent.com/39161054/371064550-ffccc825-0c63-474d-8d94-6883e86ed1e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDE4NTEsIm5iZiI6MTcyNzM0MTU1MSwicGF0aCI6Ii8zOTE2MTA1NC8zNzEwNjQ1NTAtZmZjY2M4MjUtMGM2My00NzRkLThkOTQtNjg4M2U4NmVkMWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA5MDU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNTRjYjUxOGJkYjIzOWU0NGM1ZmM2M2E5OTgwNzA4ZWRmMmQwYzFmNTBkYjM5MzczYWU0OWM4YTAxNGQ2NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L_qgaT7Dht2qb-M2OkSlyqRkJIVWTXYPILZZiNxstxY)
> > > > 
> > > > 
> > > > 这个也是 `apt` 的设计使然
> > > 
> > > 
> > > 恐怕不是，我刚刚在 Debian 上发现 `apt remove` 确实可以补全包名，上面的现象恐怕确实是我们这边的补全打包有问题
> > > 至于 oma 部分的设计，二位继续讨论
> > 
> > 
> > 那还挺奇怪的，我用虚拟机和电脑安装都是一样的。安装软件可以补全 但是卸载不行
> 
> 我的意思是，安同这边的 apt 补全恐怕有问题，oma 这边我们再研讨下怎么做

好的，辛苦

**Comment by eatradish** [comment]
修改已经合并了：https://github.com/AOSC-Dev/oma/commit/ba00990b31ace90515c2398ae2eb9d43020e4ee8 ，将在 v1.11 中包含
