### ISSUE TITLE
Incorrect parameter `--keep-config` in oma's completion files

### ISSUE THREAD

**Issue by ZeroAurora** [AOSC-Dev/oma#13]
https://github.com/AOSC-Dev/oma/blob/c25d0ba66e52e4398414319480a09c098d8fcc24/data/completions/oma.bash#L665

https://github.com/AOSC-Dev/oma/blob/c25d0ba66e52e4398414319480a09c098d8fcc24/data/completions/oma.fish#L59

The actual parameter is `--remove-config` which completely contradicts `--keep-config`

https://github.com/AOSC-Dev/oma/blob/c25d0ba66e52e4398414319480a09c098d8fcc24/src/args.rs#L187

**Comment by eatradish** [comment]
Try 664c3f5af54fe32f81f76d2dcb5830b83aa70471 ?

**Comment by eatradish** [comment]
Fixed on v1.3.16, closing...
