### ISSUE TITLE
Pager early exit - failed printing to stdout: Broken pipe

### ISSUE THREAD

**Issue by arkadijs** [AOSC-Dev/oma#16]
Early exit from pager produces panic on broken pipe:
```
$ oma list | less  # => press q
thread 'main' panicked at library/std/src/io/stdio.rs:1118:9:
failed printing to stdout: Broken pipe (os error 32)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
As a developer I understand where this is coming from yet end-user may not like seeing this.

Also would be nice to be able to force colors to pipe for `less -R`.

**Comment by eatradish** [comment]
Try https://github.com/AOSC-Dev/oma/commit/f6c8dcf1a7a9a8fb86338ee381349ddd450f0ccb ？

**Comment by arkadijs** [comment]
Solved the issue, thanks!
