### ISSUE TITLE
[Feature Request] Search in oma search pop-up tui

### ISSUE THREAD

**Issue by wxiwnd** [AOSC-Dev/oma#166]
Is there a way to search in oma search result tui? Like "less" or "vim", type in "/" to search patterns.
### For example:

`pacman -Ss python | less`

<img src="https://github.com/user-attachments/assets/cc2a0e64-b0fd-449c-8d3b-08eedda359e8" width="50%"> \
### Use "/" to search patterns in results:
<img src="https://github.com/user-attachments/assets/36ed7fb1-f6bc-4ef1-a82f-742529201f8d" width="50%"> \

**Comment by eatradish** [comment]
Sounds like a good idea, I'll add this feature (1.12, or 1.13?)

**Comment by wxiwnd** [comment]
Thank you for your message! If I have some spare time, I would be happy to contribute to this feature.

**Comment by eatradish** [comment]
> Thank you for your message! If I have some spare time, I would be happy to contribute to this feature.

Your contribution would be much appreciated!

**Comment by eatradish** [comment]
Done. thanks!
