### ISSUE TITLE
`oma topic` isn't transactional

### ISSUE THREAD

**Issue by poscat0x04** [AOSC-Dev/oma#197]
Currently, `oma topic` will still keep the modification on topic state (I think it's tracked in `/etc/apt/sources.list.d/atm.list`? I'm not sure) even if the corresponding upgrading/downgrading action fails. This is undesirable since it can lead to inconsistencies between the topic state and the installed packages. `oma topic` should rollback the changes if the upgrading/downgrading action were to fail.

**Comment by MingcongBai** [comment]
Unfortunately, I would have to close this as invalid - APT is by itself not transactional, there is no practical way for us to track (incomplete) changes, much less so reverting them half-way.
