### ISSUE TITLE
The built-in pager's keybinds are not disabled when searching

### ISSUE THREAD

**Issue by poscat0x04** [AOSC-Dev/oma#201]
When searching for text using the `/` key in the pager, navigation keys (`ijkl`) are not disabled meaning you can't type in these four characters.

To reproduce, run `oma provides /etc/xdg` and type `/jkjk`.

**Comment by eatradish** [comment]
Try https://github.com/AOSC-Dev/oma/pull/202 ?

**Comment by poscat0x04** [comment]
Does seem to solve `hjkl` issues although `q` key is still affected I think.

**Comment by eatradish** [comment]
> Does seem to solve `hjkl` issues although `q` key is still affected I think.

Try again?

**Comment by eatradish** [comment]
Fixed on v1.12.3
