### ISSUE TITLE
[Feature Request] Build .deb for non x86-64 arch

### ISSUE THREAD

**Issue by shirok1** [AOSC-Dev/oma#271]
I have some aarch64 machines running Debian and Ubuntu, and I would like to use oma to manage their packages.

Current GitHub Action workflow for building `.deb` (https://github.com/AOSC-Dev/oma/blob/master/.github/workflows/deb.yml) might not be capable of cross-building, requiring a rewrite of build process.

`docker buildx` might be helpful.

**Comment by eatradish** [comment]
Fixed on https://github.com/AOSC-Dev/oma/releases/tag/v1.13.0-rc.1
