### ISSUE TITLE
Abbreviations/aliases for verbs

### ISSUE THREAD

**Issue by OriginCode** [AOSC-Dev/oma#51]
Hi,

I wanna purpose some abbreviations/aliases for oma verbs, just for convenience when typing in my terminal :)

|Subcommands|Abbreviation|
|---|---|
|install|in|
|upgrade|up|
|download|dl|
|remove|rm|
|refresh|ref|
|search|se|
|files|fi|
|provides|pr|
|fix-broken|fb|
|history|hi|

**Comment by eatradish** [comment]
I don't think this convenience should be provided, because of the existence of the complement in the first place, this so-called short command I very much doubt will have any effect, and I'm very worried that it will lead to user confusion (like `pacman -Syyu`)

**Comment by MingcongBai** [comment]
> I don't think this convenience should be provided, as there is already a complementary function, and this so-called short command I highly doubt will have any effect, and I'm worried that it will lead to confusion (like `pacman -Syyu`)

To add a different opinion here, I think we should provide this shorthand - the issue with pacman is quite different to ours, as this is a multi-character shorthand (with a limited hint of semantics like add/rm). That said, some of the shorthands as suggested by @OriginCode can use some further deliberation.
